personas/urls.py
from django.conf.urls import url
from personas.views import Personas, CrearPersona,EditarPersona, ReportePersonasExcel, Bienvenida, DetallePersona, ModificarPersona,ReporteEDPExcel,ReporteODCExcel,ficha
from . import models
from . import views

urlpatterns = [
    #url(r'^',include('seguridad.urls',namespace='seguridad')),
    url(r'^$',views.Bienvenida.as_view(), name="bienvenida"),
    url(r'^crear_persona/$',views.CrearPersona.as_view(), name="crear_persona"),
    url(r'^personas/$',Personas.as_view(), name="personas"),
    url(r'^ficha/$',ficha.as_view(), name="ficha"),
    #url(r'^detail/(?P<dni>[-\w]+)/$',views.EditarPersona.as_view(), name="editar_persona"),
    url(r'^detail/(?P<id_Persona>\d+)/$',views.EditarPersona.as_view(), name="editar_persona"),
    url(r'^reporte_personas_excel/$',ReportePersonasExcel.as_view(), name="reporte_personas_excel"),

    url(r'^reporte_edp_excel/$',ReporteEDPExcel.as_view(), name="reporte_edp_excel"),
    url(r'^reporte_odc_excel/$',ReporteODCExcel.as_view(), name="reporte_odc_excel"),

    url(r'^detalle_persona/(?P<pk>\d+)/$', DetallePersona.as_view(), name="detalle_persona"),
    url(r'^modificar_persona/(?P<pk>\d+)/$',ModificarPersona.as_view(), name="modificar_persona"),

    url(r'^polls/$', views.upload, name='uplink'),
    url(r'^polls/import/', views.import_data, name="import"),
    url(r'^polls/import_EDP/', views.import_EDP_ODC, name="import_EDP_ODC"),
    url(r'^polls/export/(.*)', views.export_data, name="export"),
    url(r'^polls/import_sheet/', views.import_sheet, name="import_sheet"),
    url(r'^ctto/export/', views.export_r5, name="export_r5"),


    url(r'^prueba/',views.prueba, name="prueba"),

]

tutorial/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from personas.views import Personas, CrearPersona,EditarPersona, ReportePersonasExcel, Bienvenida

#admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('personas.urls',namespace='personas')),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
]

personas/forms.py
from django import forms

from .models import Persona, Ctto

class PersonaCreateForm(forms.ModelForm):

    class Meta:
        model = Persona
        fields = ('dni','nombre','apellido_paterno','apellido_materno')
        labels = {
            'apellido_paterno': 'Apellido Paterno',
            'apellido_materno': 'Apellido Materno'
        }
        widgets = {
            'dni': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido_paterno': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido_materno': forms.Textarea(attrs={'class': 'form-control'}),

        }

class CttoUpdateForm(forms.ModelForm):

    class Meta:
        model = Ctto
        fields = ['NumCtto','DescCtto','MonedaCtto','ValorCtto','IdCtta','EstCtto','FechIniCtto','IdCecoCtto','CordCtto','IdMandante' ]
        labels = {
            'FechIniCtto': 'Fecha de Inicio',
            'IdCecoCtto': 'Centro de Costo'
        }

        widgets = {
            'NumCtto': forms.TextInput(attrs={'class': 'form-control'}),
            'DescCtto': forms.TextInput(attrs={'class': 'form-control','rows':1, 'cols':60}),
            'MonedaCtto': forms.TextInput(attrs={'class': 'form-control'}),
            'ValorCtto': forms.NumberInput(attrs={'class': 'form-control'} ),
            #'IdCtta': forms.TextInput(attrs={'class': 'form-control'}),
            'EstCtto': forms.TextInput(attrs={'class': 'form-control'}),
            'FechIniCtto': forms.DateInput(format='%m/%d/%Y'),
            #'IdCecoCtto': forms.TextInput(attrs={'class': 'form-control'}),
            'CordCtto': forms.TextInput(attrs={'class': 'form-control','rows':1, 'cols':60}),
            #'IdMandante': forms.Textarea(attrs={'class': 'form-control'}),

        }

personas/views.py
from django.shortcuts import render,redirect,get_object_or_404
#encoding:utf-8
# Create your views here.
from personas.models import Persona
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView, View
from django.views.generic.detail import DetailView


from django.conf import settings
from .forms import PersonaCreateForm, CttoUpdateForm

#Workbook nos permite crear libros en excel
from openpyxl import Workbook
#Nos devuelve un objeto resultado, en este caso un archivo de excel
from django.http.response import HttpResponse

from django.db.models import Avg, Max, Min, Count, Sum

from django.core.exceptions import ObjectDoesNotExist # para cuando exista moneda

from datetime import timedelta, datetime

import date_converter

#-------------------------------------------------------------------------

#from django.shortcuts import render_to_response
from django.shortcuts import render
from django.http import HttpResponseBadRequest, JsonResponse
from django import forms
from django.template import RequestContext
import django_excel as excel
from .models import Question, Choice, Area, Ceco, Mdte, Ctta, Ctto, Edp, Odc, Monedas

# No longer you need the following import statements if you use pyexcel >=0.2.2
import pyexcel.ext.xls
import pyexcel.ext.xlsx
import pyexcel.ext.ods3   # noqa


class UploadFileForm(forms.Form):
    file = forms.FileField()

# Create your views here.
def upload(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            filehandle = request.FILES['file']
            return excel.make_response(filehandle.get_sheet(), "csv",
                                       file_name="download")
    else:
        form = UploadFileForm()
    return render_to_response(
        'upload_form.html',
        {
            'form': form,
            'title': 'Excel file upload and download example',
            'header': ('Please choose any excel file ' +
                       'from your cloned repository:')
        },
        context_instance=RequestContext(request))

def import_sheet(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST,
                              request.FILES)
        if form.is_valid():
            request.FILES['file'].save_to_database(
                name_columns_by_row=0,
                model=Ceco,
                mapdict=['IdCeco', 'IdAreas', 'CodCeco', 'NomCeco', 'Budget'])
            return HttpResponse("OK")
        else:
            return HttpResponseBadRequest()
    else:
        form = UploadFileForm()
    return render_to_response('upload_form.html',
                              {'form': form},
                              context_instance=RequestContext(request))


def import_data(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST,
                              request.FILES)

        def Ceco_func(row):
            q = Area.objects.filter(IdAreas=row[1])[0]
            row[1] = q
            return row
        def Ctto_func(row):
            print ('en Ctto')
            print (row)
            q1 = Ctta.objects.filter(IdCtta=row[5])[0]
            row[5] = q1
            q2 = Ceco.objects.filter(IdCeco=row[9])[0]
            row[9] = q2
            q3 = Mdte.objects.filter(IdMandante=row[11])[0]
            row[11] = q3
            return row
        def Edp_func(row):
            print ('en EDP')
            print (row)
            q4 = Ctto.objects.filter(IdCtto=row[1])[0]
            row[1] = q4
            return row
        def Odc_func(row):
            print(row)
            q5 = Ceco.objects.filter(IdCeco=row[2])[0]
            row[2] = q5
            q6 = Ctto.objects.filter(IdCtto=row[3])[0]
            row[3] = q6
            print('q5 y q6')
            print(q5,q6)
            return row

        if form.is_valid():
            request.FILES['file'].save_book_to_database(
                models=[Area, Ceco, Mdte, Ctta, Ctto, Edp, Odc],
                initializers=[None, Ceco_func, None, None,Ctto_func,Edp_func, Odc_func],
                mapdicts=[
                    ['IdAreas', 'NomArea', 'CodArea'],
                    ['IdCeco', 'IdAreas', 'CodCeco', 'NomCeco', 'Budget'],
                    ['IdMandante', 'NomMandte', 'DirecMandte', 'RutMandte'],
                    ['IdCtta', 'NomCtta', 'DirCtta', 'RutCtta'],
                    ['IdCtto', 'NumCtto', 'DescCtto', 'MonedaCtto', 'ValorCtto', 'IdCtta', 'EstCtto', 'FechIniCtto', 'FechTerCtto', 'IdCecoCtto', 'CordCtto', 'IdMandante',\
                    'Carpeta','TipoServ', 'AjusteCom','AjustNumEDP','AjustValEDP','AdjudicCtto','LocalCtto','TerrenCtto','SeguroCtto'],
                    ['IdEDP', 'IdCtto', 'NumEDP', 'ValEDP', 'PeriodEDP', 'DevAntEDP', 'RetEDP', 'DevRet', 'Estado', 'FactEDP'],
                    ['IdODC', 'NumODC', 'IdCecoODC', 'IdCtto', 'FechT_ODC', 'ValorODC', 'DescripODC']]

            )
            return HttpResponse("OK", status=200)
        else:
            return HttpResponseBadRequest()
    else:
        form = UploadFileForm()
    return render(request,
        'upload_form.html',
        {
            'form': form,
            'title': 'Import excel data into database example',
            'header': 'Please upload sample-data.xls:'
        })


def import_EDP_ODC(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST,
                              request.FILES)

        def Edp_func(row):
            print ('en EDP')
            print (row)
            q4 = Ctto.objects.filter(IdCtto=row[1])[0]
            row[1] = q4
            return row
        def Odc_func(row):
            print(row)
            q5 = Ceco.objects.filter(IdCeco=row[2])[0]
            row[2] = q5
            q6 = Ctto.objects.filter(IdCtto=row[3])[0]
            row[3] = q6
            print('q5 y q6')
            print(q5,q6)
            return row

        if form.is_valid():
            print('valido')
            request.FILES['file'].save_book_to_database(
                models=[Edp, Odc],
                initializers=[Edp_func, Odc_func],
                mapdicts=[
                    ['IdEDP', 'IdCtto', 'NumEDP', 'ValEDP', 'PeriodEDP', 'DevAntEDP', 'RetEDP', 'DevRet', 'Estado', 'FactEDP'],
                    ['IdODC', 'NumODC', 'IdCecoODC', 'IdCtto', 'FechT_ODC', 'ValorODC', 'DescripODC']]
            )
            return HttpResponse("OK", status=200)
        else:
            return HttpResponseBadRequest()
    else:
        form = UploadFileForm()
    return render(request,
        'upload_form.html',
        {
            'form': form,
            'title': 'Import excel data into database example',
            'header': 'Please upload sample-data.xls:'
        })
















def export_r5(request):
            column_names = ['IdCtto','NumCtto', 'DescCtto']
            exp_ctto = Ctto.objects.filter()



            e = Ctto.objects.filter()
            print(e)

            #q5 = Mdte.objects.filter(exp_ctto)
            #q6 = Ctto.objects.select_related().get(id=2)


            #print(q6.NomMandte)

            #exp_ctto = Ctto.objects.all()


            return excel.make_response_from_query_sets(
                exp_ctto,
                column_names,
                'xls',
                file_name="custom"
            )






def export_data(request, atype):
    if atype == "sheet":
        return excel.make_response_from_a_table(
            Question, 'xls', file_name="sheet")
    elif atype == "book":
        return excel.make_response_from_tables(
            [Question, Choice], 'xls', file_name="book")
    elif atype == "custom":
        question = Question.objects.get(slug='ide')
        query_sets = Choice.objects.filter(question=question)
        column_names = ['choice_text', 'id', 'votes']
        return excel.make_response_from_query_sets(
            query_sets,
            column_names,
            'xls',
            file_name="custom"
        )
    else:
        return HttpResponseBadRequest(
            "Bad request. please put one of these " +
            "in your url suffix: sheet, book or custom")










#-------------------------------------------------------------------------------






class ModificarPersona(UpdateView):
    #Especificamos que el modelo a utilizar va a ser Persona
    form_class = CttoUpdateForm

    model = Ctto
    #Establecemos que la plantilla se llamara modificar persona
    template_name = 'modificar_persona_new.html'
    #Determinamos los campos con los que se va a trabajar, esto es obligatorio sino nos saldra un error
    #fields = ['NumCtto','DescCtto','MonedaCtto','ValorCtto','IdCtta','EstCtto','FechIniCtto','IdCecoCtto','CordCtto','IdMandante' ]
    #Con esta linea establecemos que se hara despues que la operacion de modificacion se complete correctamente
    success_url = reverse_lazy('personas:personas')



class DetallePersona(DetailView):
    model = Ctto
    template_name = 'detalle_persona_new.html'


#def sumarLista(lista):
#    sum=0
#    for i in range(0,len(lista)):
#        sum=sum+lista[i]
#    return sum



def prueba(request):
    CTTOS = Ctto.objects.all()
    ODC = Odc.objects.all()
    EDP = Edp.objects.all()



    #Aux = Ctto.objects.values_list('id','IdCtto','NumCtto')
    #Aux = Ctto.objects.get(id=3)
    #Aux2 = Aux.IdCtta.NomCtta

    #Aux = list(Odc.objects.filter(IdCtto__id='3').values_list('ValorODC',flat=True))
    Aux = Odc.objects.filter(IdCtto__id=3).aggregate(Sum('ValorODC'))

    #Aux2= Ctto.objects.filter(id=3)
    #Aux = sumarLista(Aux)
    #Aux2 = Aux[0]
    Aux2 =Aux['ValorODC__sum']

    print('Aux', Aux)
    print('Aux2', Aux2)
    html="<html><body> el valor es Aux : %s  Aux2 : </body></html>" % Aux, Aux2

    return HttpResponse(html)

personas/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Ejemplo Círculo de Programadores de Python Piura</title>
        <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/jquery.dataTables.min.css"  %}"  />
        <script src="{% static "js/jquery.js" %}"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <script src="{% static "js/jquery.dataTables.min.js" %}"></script>
    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Desplegar navegación</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'personas:bienvenida' %}">
                        <span class="glyphicon glyphicon-home"></span> Inicio
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav">
                    <a class="navbar-brand" href="{% url 'personas:personas' %}">
                        <span class="glyphicon glyphicon-user"></span> Contrato

                    </a>
                    <a class="navbar-brand" href="{% url 'personas:ficha' %}">

                        <span class="glyphicon glyphicon-list"></span> Ficha
                    </a>
                    <li class="dropdown">
                        <a class="navbar-brand" data-toggle="dropdown" href="#">Reportes
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                           <li><a href="{% url 'personas:reporte_personas_excel' %}">Reporte Commitment</a></li>
                           <li><a href="{% url 'personas:reporte_edp_excel' %}">Reporte Pagos</a></li>
                           <li><a href="{% url 'personas:reporte_odc_excel' %}">Reporte Odc</a></li>
                           <li><a href="#">Reporte Mensual</a></li>
                        </ul>
                    </li>
                  </ul>
                </div>

                {% block menu %}
                {% endblock menu %}
            </nav>
            <div id="page-wrapper">
                <div class="container-fluid">
                    {% block cuerpo %}
                    {% endblock cuerpo %}
                </div>
            </div>
        </div>
    </body>
    {% block js %}
    {% endblock js %}
</html>

personas/templates/crear_edp_new.html
{% extends "CuerpoVacio.html" %}
{% block cuerpo %}

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>
              Users
              <small>
                  Some examples to get you started
              </small>
          </h3>
      </div>

          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">


                  <div class="panel-body">
                      <form role="form" action="#" method="post">
                          {% csrf_token %}
                          <div class="form-group">
                              {{ form.as_p }}
                          </div>
                          <div class='form-group'>
                              <input type="submit" class="btn btn-primary" name="submit" value="Crear Estado de Pago">
                              <button type="reset" class="btn btn-primary" onclick="location.href='{% url 'personas:personas' %}'">
                                  Cancelar
                              </button>
                          </div>
                      </form>
                  </div>

                </div>
                <div class="clearfix"></div>
              </div>
                <div class="x_content">
                  <p class="text-muted font-13 m-b-30">
                    Tablas de Servicios, Contratos y Convenios: <code>$().DataTable();</code>
                  </p>
                </div>
            </div>
          </div>
    </div>
  </div>
</div>




{% endblock cuerpo %}

{% block js %}

{% endblock js %}

personas/templates/crear_persona.html
{% extends "base.html" %}
{% block cuerpo %}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Tablas</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Crear Persona
            </div>
            <div class="panel-body">
                <form role="form" action="#" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
                    <div class='form-group'>
                        <input type="submit" class="btn btn-primary" name="submit" value="Crear Persona">
                        <button type="reset" class="btn btn-primary" onclick="location.href='{% url 'personas:personas' %}'">
                            Cancelar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="popup"></div>
{% endblock cuerpo %}

{% block js %}

{% endblock js %}

personas/templates/detalle_edp_new.html
{% extends "CuerpoVacio.html" %}

{% block cuerpo %}

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>
              Users
              <small>
                  Some examples to get you started
              </small>
          </h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                  </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Servicios <small>Users</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a href="#"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a href="#"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <p class="text-muted font-13 m-b-30">
              Tablas de Servicios, Contratos y Convenios: <code>$().DataTable();</code>
            </p>


            <div class="row">
                <div class="col-lg-12">




                      <div class="panel panel-info">

                          <div class="panel-body">
                              <div class='form-group'>
                                  <div class="row">
                                      <div class="col-md-12">
                                          <label>Edp:</label>
                                          <p>{{ object.NumEDP }}</p>
                                          <label>Descripción:</label>
                                          <p>{{ object.ValEDP }}</p>
                                          <label>Periodo Inicio: </label>
                                          <p>{{ object.PeriodEDP }}</p>
                                          <label>Periodo Término: </label>
                                          <p>{{ object.PeriodEDPTer }}</p>
                                          <label>Devolución Anticipo: </label>
                                          <p>{{ object.DevAntEDP }}</p>
                                          <label>Retenciones: </label>
                                          <p>{{ object.RetEDP }} {{object.DevRet}}</p>
                                          <td style="mso-number-format:'#,##0.000';">{{object.DevRet}}</td>


                                          <label>Estado: </label>
                                          <p>{{ object.Estado }}</p>
                                          <label>Factura: </label>
                                          <p>{{ object.FactEDP }}</p>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>



                </div>
            </div>
          </div>
        </div>
      </div>



          </div>
        </div>



  </div>




{% endblock cuerpo %}

personas/templates/detalle_persona.html
{% extends "CuerpoVacio.html" %}

{% block cuerpo %}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Contrato</h1>
    </div>
</div>



<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                Detalle del Contrato
            </div>
            <div class="panel-body">
                <div class='form-group'>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Ctto:</label>
                            <p>{{ object.NumCtto }}</p>
                            <label>Descripción:</label>
                            <p>{{ object.DescCtto }}</p>
                            <label>Centro Costo:</label>
                            <p>{{ object.IdCecoCtto.CodCeco }}</p>
                            <label>Fecha Inicio: </label>
                            <p>{{ object.FechIniCtto }}</p>
                            <label>Fecha Término: </label>
                            <p>{{ object.FechTerCtto }}</p>
                            <label>Moneda Ctto: </label>
                            <p>{{ object.MonedaCtto }}</p>
                            <label>Valor Inicial Ctto: </label>
                            <p>{{ object.MonedaCtto }} {{object.ValorCtto}}</p>
                            <td style="mso-number-format:'#,##0.000';">{{object.ValorCtto}}</td>


                            <label>Mandante: </label>
                            <p>{{ object.IdMandante.NomMandte }}</p>
                            <label>Cordinador de Ctto: </label>
                            <p>{{ object.CordCtto }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock cuerpo %}

personas/templates/editar_persona.html
{% extends "base.html" %}
{% block cuerpo %}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Tablas</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Editar Persona
            </div>
            <div class="panel-body">
                <form role="form" action="#" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
                    <div class='form-group'>
                        <input type="submit" class="btn btn-primary" name="submit" value="Crear Persona">
                        <button type="reset" class="btn btn-primary" onclick="location.href='{% url 'personas:personas' %}'">
                            Cancelar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="popup"></div>
{% endblock cuerpo %}

{% block js %}

{% endblock js %}

personas/templates/ficha.html
{% extends "base.html" %}

{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Circulo de Programadores de Python Piura</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                Bienvenido
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="row">
                        <h3 class="text-center">Ficha</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock cuerpo %}

personas/templates/modificar_persona_new.html
{% extends "CuerpoVacio.html" %}

{% block cuerpo %}

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>
              Users
              <small>
                  Some examples to get you started
              </small>
          </h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                  </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Modificar Contrato <small>Users</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a href="#"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a href="#"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <p class="text-muted font-13 m-b-30">
              Tablas de Servicios, Contratos y Convenios: <code>$().DataTable();</code>
            </p>


            <div class="row">
                <div class="col-lg-12">

                  <div class="row">
                      <div class="col-xs-8 col-xs-push-1">
                          <div class="panel panel-default">
                              <div class="panel-heading">
                                  Por favor ingrese todos los campos necesarios.
                              </div>
                              <div class="panel-body">
                                  <form role="form" method="post">
                                      {% csrf_token %}
                                      <div class="form-group">
                                          {{ form.as_p}}
                                      </div>
                                      <div class='form-group'>
                                          <input type="submit" class="btn btn-primary" name="submit" value="Modificar Persona">
                                          <button type="reset" class="btn btn-primary" onclick="location.href='{% url 'personas:personas' %}'">
                                              Cancelar
                                          </button>
                                      </div>
                                  </form>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div id="popup"></div>



                </div>
            </div>
          </div>
        </div>
      </div>



          </div>
        </div>



  </div>




{% endblock cuerpo %}

personas/templates/template_GET.html
<!DOCTYPE html>
<html>
<head>
    <title> GET </title>

</head>
<body>


</body>
</html>

personas/templates/upload_form.html
<html>
<head>
    <title>{{title}}</title>
</head>
<body>
    <h1>{{header}}</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" enctype="multipart/form-data"  method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</body>
</html>